# Generated by Django 4.1.7 on 2023-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_articulo', models.CharField(max_length=50)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('breve_descripcion', models.CharField(max_length=100)),
                ('descripcion_articulo_inicio', models.CharField(max_length=500)),
                ('descripcion_articulo_desarrollo', models.CharField(max_length=500)),
                ('descripcion_articulo_conclusion', models.CharField(max_length=500)),
            ],
        ),
    ]
