# Generated by Django 4.1.7 on 2023-03-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_articulo', models.CharField(max_length=100)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='publicaciones')),
                ('breve_descripcion', models.CharField(max_length=200)),
                ('descripcion_articulo_inicio', models.CharField(max_length=1000)),
                ('imagen_1_de_nota', models.ImageField(blank=True, null=True, upload_to='publicaciones')),
                ('descripcion_articulo_desarrollo', models.CharField(max_length=1000)),
                ('imagen_2_de_nota', models.ImageField(blank=True, null=True, upload_to='publicaciones')),
                ('descripcion_articulo_conclusion', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
